version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: -main

jobs:
  build:
    working_directory: ~/ExmapleApplication
    docker:
      - image: circleci/node:16.17.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{checksum "pachege-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "pachege-lock.json"}}
          paths:
            - ./node_modules
